// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/gelfapi/v1/chunk.proto

package gelfapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SequenceNum   int32                  `protobuf:"varint,2,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"` // 'int' in Go is usually 32 or 64 bit; int32 is standard for sequence
	SequenceCount int32                  `protobuf:"varint,3,opt,name=sequence_count,json=sequenceCount,proto3" json:"sequence_count,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // Direct mapping for []byte
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_api_gelfapi_v1_chunk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_gelfapi_v1_chunk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_api_gelfapi_v1_chunk_proto_rawDescGZIP(), []int{0}
}

func (x *Chunk) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Chunk) GetSequenceNum() int32 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *Chunk) GetSequenceCount() int32 {
	if x != nil {
		return x.SequenceCount
	}
	return 0
}

func (x *Chunk) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Chunk) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ChunkBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*Chunk               `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkBatch) Reset() {
	*x = ChunkBatch{}
	mi := &file_api_gelfapi_v1_chunk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkBatch) ProtoMessage() {}

func (x *ChunkBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_gelfapi_v1_chunk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkBatch.ProtoReflect.Descriptor instead.
func (*ChunkBatch) Descriptor() ([]byte, []int) {
	return file_api_gelfapi_v1_chunk_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkBatch) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type ChunkBatchSummary struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalChunksReceived int64                  `protobuf:"varint,1,opt,name=total_chunks_received,json=totalChunksReceived,proto3" json:"total_chunks_received,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChunkBatchSummary) Reset() {
	*x = ChunkBatchSummary{}
	mi := &file_api_gelfapi_v1_chunk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkBatchSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkBatchSummary) ProtoMessage() {}

func (x *ChunkBatchSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_gelfapi_v1_chunk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkBatchSummary.ProtoReflect.Descriptor instead.
func (*ChunkBatchSummary) Descriptor() ([]byte, []int) {
	return file_api_gelfapi_v1_chunk_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkBatchSummary) GetTotalChunksReceived() int64 {
	if x != nil {
		return x.TotalChunksReceived
	}
	return 0
}

var File_api_gelfapi_v1_chunk_proto protoreflect.FileDescriptor

const file_api_gelfapi_v1_chunk_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/gelfapi/v1/chunk.proto\x12\n" +
	"gelfapi.v1\"\xa8\x01\n" +
	"\x05Chunk\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12!\n" +
	"\fsequence_num\x18\x02 \x01(\x05R\vsequenceNum\x12%\n" +
	"\x0esequence_count\x18\x03 \x01(\x05R\rsequenceCount\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"7\n" +
	"\n" +
	"ChunkBatch\x12)\n" +
	"\x06chunks\x18\x01 \x03(\v2\x11.gelfapi.v1.ChunkR\x06chunks\"G\n" +
	"\x11ChunkBatchSummary\x122\n" +
	"\x15total_chunks_received\x18\x01 \x01(\x03R\x13totalChunksReceived2]\n" +
	"\fChunkService\x12M\n" +
	"\x10StreamChunkBatch\x12\x16.gelfapi.v1.ChunkBatch\x1a\x1d.gelfapi.v1.ChunkBatchSummary\"\x00(\x01B3Z1github.com/tomsobpl/badili/api/gelfapi/v1;gelfapib\x06proto3"

var (
	file_api_gelfapi_v1_chunk_proto_rawDescOnce sync.Once
	file_api_gelfapi_v1_chunk_proto_rawDescData []byte
)

func file_api_gelfapi_v1_chunk_proto_rawDescGZIP() []byte {
	file_api_gelfapi_v1_chunk_proto_rawDescOnce.Do(func() {
		file_api_gelfapi_v1_chunk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gelfapi_v1_chunk_proto_rawDesc), len(file_api_gelfapi_v1_chunk_proto_rawDesc)))
	})
	return file_api_gelfapi_v1_chunk_proto_rawDescData
}

var file_api_gelfapi_v1_chunk_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_gelfapi_v1_chunk_proto_goTypes = []any{
	(*Chunk)(nil),             // 0: gelfapi.v1.Chunk
	(*ChunkBatch)(nil),        // 1: gelfapi.v1.ChunkBatch
	(*ChunkBatchSummary)(nil), // 2: gelfapi.v1.ChunkBatchSummary
}
var file_api_gelfapi_v1_chunk_proto_depIdxs = []int32{
	0, // 0: gelfapi.v1.ChunkBatch.chunks:type_name -> gelfapi.v1.Chunk
	1, // 1: gelfapi.v1.ChunkService.StreamChunkBatch:input_type -> gelfapi.v1.ChunkBatch
	2, // 2: gelfapi.v1.ChunkService.StreamChunkBatch:output_type -> gelfapi.v1.ChunkBatchSummary
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_gelfapi_v1_chunk_proto_init() }
func file_api_gelfapi_v1_chunk_proto_init() {
	if File_api_gelfapi_v1_chunk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gelfapi_v1_chunk_proto_rawDesc), len(file_api_gelfapi_v1_chunk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gelfapi_v1_chunk_proto_goTypes,
		DependencyIndexes: file_api_gelfapi_v1_chunk_proto_depIdxs,
		MessageInfos:      file_api_gelfapi_v1_chunk_proto_msgTypes,
	}.Build()
	File_api_gelfapi_v1_chunk_proto = out.File
	file_api_gelfapi_v1_chunk_proto_goTypes = nil
	file_api_gelfapi_v1_chunk_proto_depIdxs = nil
}
