// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/gelfapi/v1/message.proto

package gelfapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	ShortMessage  string                 `protobuf:"bytes,3,opt,name=short_message,json=shortMessage,proto3" json:"short_message,omitempty"`
	FullMessage   string                 `protobuf:"bytes,4,opt,name=full_message,json=fullMessage,proto3" json:"full_message,omitempty"`
	Timestamp     float64                `protobuf:"fixed64,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Extras        *structpb.Struct       `protobuf:"bytes,7,opt,name=extras,proto3" json:"extras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_gelfapi_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_gelfapi_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_gelfapi_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Message) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Message) GetShortMessage() string {
	if x != nil {
		return x.ShortMessage
	}
	return ""
}

func (x *Message) GetFullMessage() string {
	if x != nil {
		return x.FullMessage
	}
	return ""
}

func (x *Message) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Message) GetExtras() *structpb.Struct {
	if x != nil {
		return x.Extras
	}
	return nil
}

type MessageBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBatch) Reset() {
	*x = MessageBatch{}
	mi := &file_api_gelfapi_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBatch) ProtoMessage() {}

func (x *MessageBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_gelfapi_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBatch.ProtoReflect.Descriptor instead.
func (*MessageBatch) Descriptor() ([]byte, []int) {
	return file_api_gelfapi_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageBatch) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MessageBatchSummary struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalMessagesReceived int64                  `protobuf:"varint,1,opt,name=total_messages_received,json=totalMessagesReceived,proto3" json:"total_messages_received,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MessageBatchSummary) Reset() {
	*x = MessageBatchSummary{}
	mi := &file_api_gelfapi_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBatchSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBatchSummary) ProtoMessage() {}

func (x *MessageBatchSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_gelfapi_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBatchSummary.ProtoReflect.Descriptor instead.
func (*MessageBatchSummary) Descriptor() ([]byte, []int) {
	return file_api_gelfapi_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *MessageBatchSummary) GetTotalMessagesReceived() int64 {
	if x != nil {
		return x.TotalMessagesReceived
	}
	return 0
}

var File_api_gelfapi_v1_message_proto protoreflect.FileDescriptor

const file_api_gelfapi_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1capi/gelfapi/v1/message.proto\x12\n" +
	"gelfapi.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xe4\x01\n" +
	"\aMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12#\n" +
	"\rshort_message\x18\x03 \x01(\tR\fshortMessage\x12!\n" +
	"\ffull_message\x18\x04 \x01(\tR\vfullMessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x01R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\x12/\n" +
	"\x06extras\x18\a \x01(\v2\x17.google.protobuf.StructR\x06extras\"?\n" +
	"\fMessageBatch\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.gelfapi.v1.MessageR\bmessages\"M\n" +
	"\x13MessageBatchSummary\x126\n" +
	"\x17total_messages_received\x18\x01 \x01(\x03R\x15totalMessagesReceived2e\n" +
	"\x0eMessageService\x12S\n" +
	"\x12StreamMessageBatch\x12\x18.gelfapi.v1.MessageBatch\x1a\x1f.gelfapi.v1.MessageBatchSummary\"\x00(\x01B3Z1github.com/tomsobpl/badili/api/gelfapi/v1;gelfapib\x06proto3"

var (
	file_api_gelfapi_v1_message_proto_rawDescOnce sync.Once
	file_api_gelfapi_v1_message_proto_rawDescData []byte
)

func file_api_gelfapi_v1_message_proto_rawDescGZIP() []byte {
	file_api_gelfapi_v1_message_proto_rawDescOnce.Do(func() {
		file_api_gelfapi_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gelfapi_v1_message_proto_rawDesc), len(file_api_gelfapi_v1_message_proto_rawDesc)))
	})
	return file_api_gelfapi_v1_message_proto_rawDescData
}

var file_api_gelfapi_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_gelfapi_v1_message_proto_goTypes = []any{
	(*Message)(nil),             // 0: gelfapi.v1.Message
	(*MessageBatch)(nil),        // 1: gelfapi.v1.MessageBatch
	(*MessageBatchSummary)(nil), // 2: gelfapi.v1.MessageBatchSummary
	(*structpb.Struct)(nil),     // 3: google.protobuf.Struct
}
var file_api_gelfapi_v1_message_proto_depIdxs = []int32{
	3, // 0: gelfapi.v1.Message.extras:type_name -> google.protobuf.Struct
	0, // 1: gelfapi.v1.MessageBatch.messages:type_name -> gelfapi.v1.Message
	1, // 2: gelfapi.v1.MessageService.StreamMessageBatch:input_type -> gelfapi.v1.MessageBatch
	2, // 3: gelfapi.v1.MessageService.StreamMessageBatch:output_type -> gelfapi.v1.MessageBatchSummary
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_gelfapi_v1_message_proto_init() }
func file_api_gelfapi_v1_message_proto_init() {
	if File_api_gelfapi_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gelfapi_v1_message_proto_rawDesc), len(file_api_gelfapi_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gelfapi_v1_message_proto_goTypes,
		DependencyIndexes: file_api_gelfapi_v1_message_proto_depIdxs,
		MessageInfos:      file_api_gelfapi_v1_message_proto_msgTypes,
	}.Build()
	File_api_gelfapi_v1_message_proto = out.File
	file_api_gelfapi_v1_message_proto_goTypes = nil
	file_api_gelfapi_v1_message_proto_depIdxs = nil
}
